"""Add AssistantMessage table

Revision ID: 83a1ff42117f
Revises: e72592f964e1
Create Date: 2025-09-05 20:34:53.596252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a1ff42117f'
down_revision = 'e72592f964e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_message_timestamp'))

    op.drop_table('assistant_message')
    # ### end Alembic commands ###
