"""Add audio and transcription fields to Message

Revision ID: a34b0a28b2dc
Revises: dbf13dcf885e
Create Date: 2025-08-27 22:33:17.993431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34b0a28b2dc'
down_revision = 'dbf13dcf885e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('transcription', sa.Text(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('transcription')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
