"""Add tools column to Assistant

Revision ID: cc05226fc79c
Revises: 83a1ff42117f
Create Date: 2025-09-09 13:28:33.529895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc05226fc79c'
down_revision = '83a1ff42117f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tools', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.drop_column('tools')

    # ### end Alembic commands ###
