"""Add google_credentials to User model

Revision ID: e72592f964e1
Revises: 7fe07514e1de
Create Date: 2025-09-03 23:39:10.556641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72592f964e1'
down_revision = '7fe07514e1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_credentials_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_credentials_json')

    # ### end Alembic commands ###
